2019-04-02 00:21:35|010001|app_logic1|[04-02 00:21:35]p28796{log:132}ERROR-export(rpc_sub_player_mgr).load_player('\x92\x91\xce\x0b\xeb\xe9\x11\x80'):
Traceback (most recent call last):
  File "D:\2018\ddt\ddt\new_server\server\code\lib\grpc\rpc.py", line 668, in _handle_request_call
    log_except('export(%s).%s(%s)', obj_id, name, repr(argkw))
  File "D:\2018\ddt\ddt\new_server\server\code\lib\corelib\log.py", line 122, in log_except
    st = traceback.extract_stack(f=ei[2].tb_frame.f_back)
  ****** Traceback ******  
  File "D:\2018\ddt\ddt\new_server\server\code\lib\grpc\rpc.py", line 660, in _handle_request_call
    rs = func(*args, **kw) if kw is not None else func(*args)
  File "D:\2018\ddt\ddt\new_server\server\code\game\mgr\player.py", line 596, in load_player
    p = Player.load_player(pid)
  File "D:\2018\ddt\ddt\new_server\server\code\game\core\player.py", line 233, in load_player
    p = cls()
  File "D:\2018\ddt\ddt\new_server\server\code\lib\corelib\message.py", line 133, in __init__
    t(self, *a, **kw)
  File "D:\2018\ddt\ddt\new_server\server\code\game\core\player.py", line 157, in __init__
    self.mail = PlayerMail(self)  # 邮件
NameError: global name 'PlayerMail' is not defined

